using System.Collections.ObjectModel;using System.Windows;using System.Windows.Controls;using System.Windows.Data;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;
namespace AulaControlTeacher;
public class MainWindow:Window{
 const string LOGO="https://ia803101.us.archive.org/6/items/logos_20211117/color%20transparente.png";static readonly SolidColorBrush Green=new(Color.FromRgb(15,90,60)),Dark=new(Color.FromRgb(8,56,38)),Orange=new(Color.FromRgb(243,107,33)),Ink=new(Color.FromRgb(28,43,36)),Muted=new(Color.FromRgb(94,111,103)),Canvas=new(Color.FromRgb(244,248,246));
 readonly ObservableCollection<Device> devices=new();readonly DataGrid grid=new(){SelectionMode=DataGridSelectionMode.Extended,AutoGenerateColumns=false,IsReadOnly=true,CanUserAddRows=false,RowHeight=54,HeadersVisibility=DataGridHeadersVisibility.Column,GridLinesVisibility=DataGridGridLinesVisibility.Horizontal,Background=Brushes.White,BorderThickness=new Thickness(0),AlternatingRowBackground=new SolidColorBrush(Color.FromRgb(249,251,250))};readonly TextBlock footer=new(){Foreground=Muted};readonly TextBlock statOnline=new(),statSupervised=new(),statAvailable=new(),statAlerts=new();Settings settings;Discovery? discovery;Commands? commands;Registry? registry;readonly DispatcherTimer timer=new(){Interval=TimeSpan.FromSeconds(2)};
 public MainWindow(){Title="AulaControl · Consola docente";Width=1440;Height=840;MinWidth=1050;MinHeight=650;WindowStartupLocation=WindowStartupLocation.CenterScreen;Background=Canvas;FontFamily=new FontFamily("Segoe UI");settings=Settings.Load();BuildUi();timer.Tick+=(_,_)=>Refresh();timer.Start();Loaded+=(_,_)=>Configure();Closed+=(_,_)=>discovery?.Dispose();}
 Button B(string s,RoutedEventHandler h,SolidColorBrush? bg=null){var b=new Button{Content=s,Padding=new Thickness(15,9,15,9),Margin=new Thickness(4),Background=bg??Brushes.White,Foreground=bg==null?Ink:Brushes.White,BorderThickness=new Thickness(bg==null?1:0),BorderBrush=new SolidColorBrush(Color.FromRgb(216,225,220)),FontWeight=FontWeights.SemiBold,Cursor=System.Windows.Input.Cursors.Hand};b.Click+=h;return b;}
 Border Card(UIElement child,double pad=16){return new Border{Background=Brushes.White,CornerRadius=new CornerRadius(16),Padding=new Thickness(pad),BorderBrush=new SolidColorBrush(Color.FromRgb(226,233,229)),BorderThickness=new Thickness(1),Child=child};}
 Border Stat(string title,string caption,TextBlock value,SolidColorBrush accent){value.FontSize=29;value.FontWeight=FontWeights.Bold;value.Foreground=Ink;value.Text="0";var s=new StackPanel();var tag=new Border{Background=new SolidColorBrush(Color.FromArgb(24,accent.Color.R,accent.Color.G,accent.Color.B)),CornerRadius=new CornerRadius(10),Padding=new Thickness(9,4,9,4),HorizontalAlignment=HorizontalAlignment.Left,Child=new TextBlock{Text=title,Foreground=accent,FontWeight=FontWeights.SemiBold,FontSize=12}};s.Children.Add(tag);s.Children.Add(value);s.Children.Add(new TextBlock{Text=caption,Foreground=Muted,FontSize=12});var c=Card(s,14);c.Margin=new Thickness(5);return c;}
 Image Logo(){var i=new Image{Width=72,Height=72,Stretch=Stretch.Uniform,Margin=new Thickness(0,0,15,0)};try{i.Source=new BitmapImage(new Uri(LOGO,UriKind.Absolute));}catch{}return i;}
 void BuildUi(){var root=new Grid();root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(118)});root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(108)});root.RowDefinitions.Add(new RowDefinition());root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(38)});
 var head=new Border{Background=Dark,Padding=new Thickness(26,17,26,17)};var hg=new Grid();hg.ColumnDefinitions.Add(new ColumnDefinition());hg.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var left=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var logoBox=new Border{Background=Brushes.White,CornerRadius=new CornerRadius(16),Padding=new Thickness(8),Child=Logo()};left.Children.Add(logoBox);var titles=new StackPanel{VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(16,0,0,0)};titles.Children.Add(new TextBlock{Text="AulaControl",Foreground=Brushes.White,FontSize=31,FontWeight=FontWeights.Bold});titles.Children.Add(new TextBlock{Text="Consola docente · Gestión y supervisión de tablets",Foreground=new SolidColorBrush(Color.FromRgb(204,231,218)),FontSize=14,Margin=new Thickness(0,2,0,0)});left.Children.Add(titles);hg.Children.Add(left);var right=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var version=new Border{Background=new SolidColorBrush(Color.FromRgb(19,108,73)),CornerRadius=new CornerRadius(12),Padding=new Thickness(12,7,12,7),Margin=new Thickness(0,0,10,0),Child=new TextBlock{Text="AulaControl 1.1 Managed",Foreground=Brushes.White,FontWeight=FontWeights.SemiBold}};right.Children.Add(version);right.Children.Add(B("⚙  Configuración",(_,_)=>ConfigDialog(),Orange));Grid.SetColumn(right,1);hg.Children.Add(right);head.Child=hg;root.Children.Add(head);var accent=new Border{Background=Orange,Height=4,VerticalAlignment=VerticalAlignment.Bottom};root.Children.Add(accent);
 var stats=new Grid{Margin=new Thickness(20,10,20,6)};for(int i=0;i<4;i++)stats.ColumnDefinitions.Add(new ColumnDefinition());stats.Children.Add(Stat("EN LÍNEA","dispositivos visibles",statOnline,Green));var s2=Stat("SUPERVISADAS","sesiones con imagen activa",statSupervised,Green);Grid.SetColumn(s2,1);stats.Children.Add(s2);var s3=Stat("DISPONIBLES","sin estudiante conectado",statAvailable,new SolidColorBrush(Color.FromRgb(52,99,168)));Grid.SetColumn(s3,2);stats.Children.Add(s3);var s4=Stat("ATENCIÓN","sesiones sin supervisión",statAlerts,Orange);Grid.SetColumn(s4,3);stats.Children.Add(s4);Grid.SetRow(stats,1);root.Children.Add(stats);
 var area=new Grid{Margin=new Thickness(24,8,24,14)};area.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});area.RowDefinitions.Add(new RowDefinition());var barPanel=new WrapPanel{VerticalAlignment=VerticalAlignment.Center};barPanel.Children.Add(B("✓  Seleccionar en línea",(_,_)=>SelectOnline()));barPanel.Children.Add(B("✉  Mensaje",async(_,_)=>await PromptSend("MESSAGE","Mensaje al estudiante")));barPanel.Children.Add(B("↗  Abrir enlace",async(_,_)=>await PromptSend("OPEN_URL","URL completa (https://…)")));barPanel.Children.Add(B("▣  Ver pantalla",async(_,_)=>await Viewer(),Green));barPanel.Children.Add(B("▦  Mosaico",(_,_)=>Mosaic(),Green));barPanel.Children.Add(B("⏏  Cerrar sesión",async(_,_)=>await Send("FORCE_LOGOUT"),Orange));barPanel.Children.Add(B("↻  Probar conexión",async(_,_)=>await Send("PING")));barPanel.Children.Add(B("Limpiar offline",(_,_)=>Clean()));var toolbar=Card(barPanel,9);toolbar.Margin=new Thickness(0,0,0,12);area.Children.Add(toolbar);
 grid.ItemsSource=devices;grid.ColumnHeaderStyle=new Style(typeof(DataGridColumnHeader)){Setters={new Setter(Control.BackgroundProperty,new SolidColorBrush(Color.FromRgb(238,244,241))),new Setter(Control.ForegroundProperty,Dark),new Setter(Control.FontWeightProperty,FontWeights.SemiBold),new Setter(Control.PaddingProperty,new Thickness(10,11,10,11)),new Setter(Control.BorderBrushProperty,new SolidColorBrush(Color.FromRgb(222,231,226)))}};AddCol("Estado","Status",110);AddCol("Dispositivo","Name",150);AddCol("Estudiante / usuario","Person",210);AddCol("Curso","CourseText",115);AddCol("Supervisión","Supervision",135);AddCol("Gestión","Protection",135);AddCol("Batería","Battery",75,"{0}%");AddCol("Imagen","FrameText",75);AddCol("Modelo","Model",180);AddCol("Android","Android",75);AddCol("IP","Ip",120);AddCol("Último aviso","SeenText",95);var gridCard=Card(grid,0);Grid.SetRow(gridCard,1);area.Children.Add(gridCard);Grid.SetRow(area,2);root.Children.Add(area);
 var foot=new Border{Background=new SolidColorBrush(Color.FromRgb(229,237,233)),Padding=new Thickness(18,9,18,9),Child=footer};Grid.SetRow(foot,3);root.Children.Add(foot);Content=root;}
 void AddCol(string h,string b,double w,string? fmt=null){var x=new DataGridTextColumn{Header=h,Binding=new Binding(b),Width=w};if(fmt!=null)((Binding)x.Binding).StringFormat=fmt;grid.Columns.Add(x);}void Configure(){if(string.IsNullOrWhiteSpace(settings.Key)){var k=Ask("Configuración inicial","Clave técnica del aula / establecimiento",true);if(string.IsNullOrWhiteSpace(k)||k.Length<10){footer.Text="Configura una clave técnica para comenzar.";return;}settings.Key=k;settings.Save();}Start();}
 void Start(){discovery?.Dispose();devices.Clear();registry=new Registry(settings.Key);foreach(var x in registry.Load())devices.Add(x);commands=new Commands(settings.Key);discovery=new Discovery(settings.Key);discovery.Seen+=Incoming;try{discovery.Start();footer.Text="● Consola activa · esperando tablets AulaControl en la red local (UDP 45888)";}catch(Exception e){footer.Text="No se pudo abrir UDP 45888: "+e.Message;}}
 void Incoming(Device n)=>Dispatcher.Invoke(()=>{var d=devices.FirstOrDefault(x=>x.Id==n.Id);if(d==null){devices.Add(n);if(!string.IsNullOrWhiteSpace(n.User))SessionLog.Change(n.Id,"",n.User,n.Course);}else{string old=d.User;d.DeviceName=n.DeviceName;d.User=n.User;d.Course=n.Course;d.Model=n.Model;d.Android=n.Android;d.Ip=n.Ip;d.CommandPort=n.CommandPort;d.ScreenPort=n.ScreenPort;d.Battery=n.Battery;d.Screen=n.Screen;d.Managed=n.Managed;d.FrameAgeMs=n.FrameAgeMs;d.Seen=DateTime.Now;d.Identity();if(old!=d.User)SessionLog.Change(d.Id,old,d.User,d.Course);}registry?.Save(devices);Refresh();});
 void Refresh(){foreach(var d in devices)d.Computed();var on=devices.Where(x=>x.IsOnline).ToList();statOnline.Text=on.Count.ToString();statSupervised.Text=on.Count(x=>x.Supervision.Contains("Supervisada")).ToString();statAvailable.Text=on.Count(x=>string.IsNullOrWhiteSpace(x.User)).ToString();statAlerts.Text=on.Count(x=>!string.IsNullOrWhiteSpace(x.User)&&!x.Supervision.Contains("Supervisada")).ToString();}
 List<Device> Sel()=>grid.SelectedItems.Cast<Device>().ToList();async Task Send(string a,string v=""){var s=Sel();if(s.Count==0){MessageBox.Show("Selecciona al menos una tablet.","AulaControl");return;}var tasks=s.Where(x=>x.IsOnline).Select(async d=>(d,await commands!.Send(d,a,v))).ToList();var rs=await Task.WhenAll(tasks);foreach(var x in rs)if(!x.Item2.Item1)footer.Text=$"{x.d.Name}: {x.Item2.Item2}";}
 async Task PromptSend(string a,string title){var x=Ask(title,a=="MESSAGE"?"Escribe el mensaje que recibirá el estudiante":"Escribe la URL completa",false);if(!string.IsNullOrWhiteSpace(x))await Send(a,x);}void SelectOnline(){grid.SelectedItems.Clear();foreach(var d in devices.Where(x=>x.IsOnline))grid.SelectedItems.Add(d);}void Clean(){foreach(var d in devices.Where(x=>!x.IsOnline).ToList())devices.Remove(d);registry?.Save(devices);Refresh();}
 async Task Viewer(){var s=Sel();if(s.Count!=1){MessageBox.Show("Selecciona una sola tablet.","AulaControl");return;}var d=s[0];if(!d.IsOnline){MessageBox.Show("El dispositivo no está conectado.","AulaControl");return;}if(!d.Screen||d.FrameAgeMs<0||d.FrameAgeMs>7000){await commands!.Send(d,"REQUEST_SCREEN");MessageBox.Show("La sesión de esa tablet no tiene supervisión activa. AulaControl la mantendrá bloqueada hasta que el estudiante complete el inicio de sesión.","Supervisión requerida");return;}new ViewerWindow(d,settings.Key){Owner=this}.Show();}
 void Mosaic(){var x=devices.Where(d=>d.IsOnline&&d.Screen&&d.FrameAgeMs>=0&&d.FrameAgeMs<7000).ToList();if(x.Count==0){MessageBox.Show("No hay sesiones supervisadas disponibles.","AulaControl");return;}new MosaicWindow(x,settings.Key){Owner=this}.Show();}
 void ConfigDialog(){var k=Ask("Configuración","Clave técnica del aula / establecimiento",true,settings.Key);if(!string.IsNullOrWhiteSpace(k)&&k.Length>=10){settings.Key=k;settings.Save();Start();}}
 string? Ask(string title,string help,bool password,string initial=""){var w=new Window{Title=title,Width=540,Height=280,ResizeMode=ResizeMode.NoResize,WindowStartupLocation=WindowStartupLocation.CenterOwner,Owner=this,Background=Canvas};var p=new StackPanel{Margin=new Thickness(28)};p.Children.Add(new TextBlock{Text=title,FontSize=24,FontWeight=FontWeights.Bold,Foreground=Dark});p.Children.Add(new TextBlock{Text=help,Margin=new Thickness(0,7,0,14),TextWrapping=TextWrapping.Wrap,Foreground=Muted});Control input;if(password){var q=new PasswordBox{FontSize=17,Padding=new Thickness(12),Password=initial,Background=Brushes.White};input=q;}else{var q=new TextBox{FontSize=17,Padding=new Thickness(12),Text=initial,Background=Brushes.White};input=q;}p.Children.Add(input);var ok=B("Aceptar",(_,_)=>w.DialogResult=true,Green);ok.Margin=new Thickness(0,16,0,0);p.Children.Add(ok);w.Content=p;if(w.ShowDialog()!=true)return null;return password?((PasswordBox)input).Password:((TextBox)input).Text.Trim();}
}
