using System.ComponentModel;using System.Runtime.CompilerServices;using System.Security.Cryptography;using System.Text;using System.Text.Json;using System.Text.Json.Serialization;using System.IO;
namespace AulaControlTeacher;
public class Device:INotifyPropertyChanged{
 string dn="",user="",course="",role="",model="",ip="",android="";int bat=-1;bool screen,managed;long frameAge=-1;DateTime seen;
 public string Id{get;set;}="";public string DeviceName{get=>dn;set=>Set(ref dn,value);}public string User{get=>user;set=>Set(ref user,value);}public string Course{get=>course;set=>Set(ref course,value);}public string Role{get=>role;set=>Set(ref role,value);}public string Model{get=>model;set=>Set(ref model,value);}public string Ip{get=>ip;set=>Set(ref ip,value);}public string Android{get=>android;set=>Set(ref android,value);}public int CommandPort{get;set;}=45901;public int ScreenPort{get;set;}=45902;public int Battery{get=>bat;set=>Set(ref bat,value);}public bool Screen{get=>screen;set{Set(ref screen,value);On(nameof(Supervision));}}public bool Managed{get=>managed;set{Set(ref managed,value);On(nameof(Protection));}}public long FrameAgeMs{get=>frameAge;set{Set(ref frameAge,value);On(nameof(Supervision));On(nameof(FrameText));}}
 public DateTime Seen{get=>seen;set{Set(ref seen,value);On(nameof(Status));On(nameof(SeenText));On(nameof(Supervision));}}
 public string Name=>string.IsNullOrWhiteSpace(DeviceName)?Id:DeviceName;public string Person=>string.IsNullOrWhiteSpace(User)?"Sin sesión":User;public string CourseText=>string.IsNullOrWhiteSpace(Course)?"—":Course;public string RoleText=>Role=="teacher"?"Profesor":Role=="student"?"Estudiante":"—";public string IdentityText=>string.IsNullOrWhiteSpace(User)?"Sin sesión":RoleText+(string.IsNullOrWhiteSpace(Course)?"":" · "+Course);public bool IsOnline=>DateTime.Now-Seen<TimeSpan.FromSeconds(9);public string Status=>IsOnline?"● En línea":"○ Sin conexión";public string Protection=>Managed?"🔒 Administrada":"⚠ Modo básico";
 public string Supervision=>!IsOnline?"○ Sin conexión":string.IsNullOrWhiteSpace(User)?"○ Disponible":Screen&&FrameAgeMs>=0&&FrameAgeMs<7000?"● Supervisada":Screen?"◐ Señal lenta":"● Bloqueada";public string FrameText=>FrameAgeMs<0?"—":FrameAgeMs<1000?"Ahora":$"{FrameAgeMs/1000.0:0.0}s";public string SeenText=>Seen==default?"—":Seen.ToString("HH:mm:ss");
 public event PropertyChangedEventHandler? PropertyChanged;public void Computed(){On(nameof(Status));On(nameof(IsOnline));On(nameof(SeenText));On(nameof(Supervision));}public void Identity(){On(nameof(Name));On(nameof(Person));On(nameof(CourseText));On(nameof(RoleText));On(nameof(IdentityText));}
 void Set<T>(ref T f,T v,[CallerMemberName]string? n=null){if(Equals(f,v))return;f=v;On(n);if(n==nameof(DeviceName))On(nameof(Name));if(n==nameof(User)){On(nameof(Person));On(nameof(Supervision));On(nameof(IdentityText));}if(n==nameof(Course)){On(nameof(CourseText));On(nameof(IdentityText));}if(n==nameof(Role)){On(nameof(RoleText));On(nameof(IdentityText));}}void On(string? n)=>PropertyChanged?.Invoke(this,new(n));}
public static class AcCrypto{
 public static string Sha(string s)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s))).ToLowerInvariant();
 public static string Hmac(string k,string d){using var h=new HMACSHA256(Encoding.UTF8.GetBytes(k));return Convert.ToHexString(h.ComputeHash(Encoding.UTF8.GetBytes(d))).ToLowerInvariant();}
 static byte[] Key(string k)=>SHA256.HashData(Encoding.UTF8.GetBytes(k));
 public static byte[] Seal(string k,byte[] plain){byte[] nonce=RandomNumberGenerator.GetBytes(12),cipher=new byte[plain.Length],tag=new byte[16];using var g=new AesGcm(Key(k),16);g.Encrypt(nonce,plain,cipher,tag);byte[] outb=new byte[12+cipher.Length+16];Buffer.BlockCopy(nonce,0,outb,0,12);Buffer.BlockCopy(cipher,0,outb,12,cipher.Length);Buffer.BlockCopy(tag,0,outb,12+cipher.Length,16);return outb;}
 public static byte[] Open(string k,byte[] sealedData){if(sealedData==null||sealedData.Length<28)throw new CryptographicException("Invalid AulaControl encrypted payload");int clen=sealedData.Length-28;byte[] nonce=new byte[12],cipher=new byte[clen],tag=new byte[16],plain=new byte[clen];Buffer.BlockCopy(sealedData,0,nonce,0,12);Buffer.BlockCopy(sealedData,12,cipher,0,clen);Buffer.BlockCopy(sealedData,12+clen,tag,0,16);using var g=new AesGcm(Key(k),16);g.Decrypt(nonce,cipher,tag,plain);return plain;}
 public static string SealText(string k,string s)=>Convert.ToBase64String(Seal(k,Encoding.UTF8.GetBytes(s??"")));public static string OpenText(string k,string s)=>Encoding.UTF8.GetString(Open(k,Convert.FromBase64String(s)));
}
public class Settings{
 [JsonIgnore] public string Key{get;set;}="";public string ProtectedKey{get;set;}="";static string Dir=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AulaControl");static string File=>Path.Combine(Dir,"settings.json");static readonly byte[] Entropy=Encoding.UTF8.GetBytes("AulaControl-Teacher-v1");
 static string Protect(string v){if(string.IsNullOrWhiteSpace(v))return "";try{return Convert.ToBase64String(ProtectedData.Protect(Encoding.UTF8.GetBytes(v),Entropy,DataProtectionScope.CurrentUser));}catch{return "";}}static string Unprotect(string v){if(string.IsNullOrWhiteSpace(v))return "";try{return Encoding.UTF8.GetString(ProtectedData.Unprotect(Convert.FromBase64String(v),Entropy,DataProtectionScope.CurrentUser));}catch{return "";}}
 public static Settings Load(){try{if(!System.IO.File.Exists(File))return new();string raw=System.IO.File.ReadAllText(File);var s=JsonSerializer.Deserialize<Settings>(raw)??new();s.Key=Unprotect(s.ProtectedKey);if(string.IsNullOrWhiteSpace(s.Key)){try{using var d=JsonDocument.Parse(raw);if(d.RootElement.TryGetProperty("Key",out var k)){s.Key=k.GetString()??"";if(!string.IsNullOrWhiteSpace(s.Key))s.Save();}}catch{}}return s;}catch{return new();}}public void Save(){Directory.CreateDirectory(Dir);ProtectedKey=Protect(Key);System.IO.File.WriteAllText(File,JsonSerializer.Serialize(new Settings{ProtectedKey=ProtectedKey}));}}
public class Registry{readonly string file;public Registry(string key){var d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AulaControl");Directory.CreateDirectory(d);file=Path.Combine(d,"devices-"+AcCrypto.Sha(key)[..12]+".json");}public List<Device> Load(){try{var list=System.IO.File.Exists(file)?JsonSerializer.Deserialize<List<Device>>(System.IO.File.ReadAllText(file))??new():new();foreach(var x in list){x.User="";x.Course="";x.Role="";}return list;}catch{return new();}}public void Save(IEnumerable<Device> d){try{var safe=d.Select(x=>new Device{Id=x.Id,DeviceName=x.DeviceName,Model=x.Model,Ip=x.Ip,Android=x.Android,CommandPort=x.CommandPort,ScreenPort=x.ScreenPort,Battery=x.Battery,Managed=x.Managed,Seen=x.Seen,FrameAgeMs=-1,Screen=false,User="",Course="",Role=""}).ToList();System.IO.File.WriteAllText(file,JsonSerializer.Serialize(safe));}catch{}}}
public static class SessionLog{
 static readonly object Gate=new();
 static string File{get{var d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AulaMovil");Directory.CreateDirectory(d);return Path.Combine(d,"session-accountability.csv");}}
 public static void Change(string id,string oldU,string newU,string course){lock(Gate){
  Ensure();
  string ev=string.IsNullOrWhiteSpace(newU)?"LOGOUT":string.IsNullOrWhiteSpace(oldU)?"LOGIN":"CHANGE";
  string responsible=string.IsNullOrWhiteSpace(newU)?oldU:newU;
  System.IO.File.AppendAllText(File,$"{Csv(DateTime.Now.ToString("O"))},{Csv(id)},{Csv(ev)},{Csv(Clean(responsible))},{Csv(Clean(course))}\r\n",Encoding.UTF8);
 }}
 static void Ensure(){if(!System.IO.File.Exists(File))System.IO.File.WriteAllText(File,"timestamp,device_id,event,user,course\r\n",Encoding.UTF8);}
 static string Clean(string s)=>string.Join(' ',(s??"").Split(' ',StringSplitOptions.RemoveEmptyEntries)).Trim();
 static string Csv(string s)=>"\""+(s??"").Replace("\"","\"\"")+"\"";
}
