using System.IO;using System.Windows;using System.Windows.Controls;using System.Windows.Media;
namespace AulaControlTeacher;
public class PrivacyNoticeWindow:Window{
 static readonly Brush Green=new SolidColorBrush(Color.FromRgb(15,90,60)),Dark=new SolidColorBrush(Color.FromRgb(8,56,38)),Orange=new SolidColorBrush(Color.FromRgb(243,107,33)),Muted=new SolidColorBrush(Color.FromRgb(94,111,103)),Bg=new SolidColorBrush(Color.FromRgb(244,248,246));
 public static string FlagFile{get{var d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AulaControl");Directory.CreateDirectory(d);return Path.Combine(d,"privacy-notice-1.1.2.ok");}}
 public static bool Seen=>File.Exists(FlagFile);
 public PrivacyNoticeWindow(){Title="AulaControl · Privacidad y seguridad";Width=720;Height=700;MinWidth=650;MinHeight=620;WindowStartupLocation=WindowStartupLocation.CenterScreen;ResizeMode=ResizeMode.CanResize;Background=Bg;FontFamily=new FontFamily("Segoe UI");Build();}
 TextBlock T(string s,double z,bool bold=false,Brush? c=null){return new TextBlock{Text=s,FontSize=z,FontWeight=bold?FontWeights.SemiBold:FontWeights.Normal,Foreground=c??Brushes.Black,TextWrapping=TextWrapping.Wrap,LineHeight=z*1.45};}
 Border Card(UIElement c){return new Border{Background=Brushes.White,CornerRadius=new CornerRadius(18),Padding=new Thickness(24),BorderBrush=new SolidColorBrush(Color.FromRgb(222,232,227)),BorderThickness=new Thickness(1),Child=c};}
 void Add(StackPanel p,string h,string b){var x=T(h,15,true,Dark);x.Margin=new Thickness(0,10,0,2);p.Children.Add(x);p.Children.Add(T(b,14,false,Muted));}
 void Build(){var sc=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto};var root=new StackPanel{Margin=new Thickness(30)};sc.Content=root;root.Children.Add(T("AulaControl",34,true,Dark));var st=T("Privacidad y seguridad",19,true,Orange);st.Margin=new Thickness(0,2,0,18);root.Children.Add(st);var p=new StackPanel();p.Children.Add(T("Tus credenciales personales no forman parte del monitoreo",23,true,Dark));var intro=T("AulaControl supervisa dispositivos institucionales sin capturar las claves personales del usuario.",15,false,Muted);intro.Margin=new Thickness(0,8,0,8);p.Children.Add(intro);Add(p,"✓ No captura contraseñas","AulaControl no solicita, registra, almacena ni transmite contraseñas personales, PIN, credenciales de cuentas, tokens de autenticación ni claves ingresadas por el usuario.");Add(p,"✓ Sin keylogging","No registra pulsaciones del teclado ni crea historiales de textos o credenciales escritas.");Add(p,"✓ Supervisión local","La consola docente recibe la pantalla en vivo y datos técnicos mínimos dentro de la red institucional configurada.");Add(p,"✓ Datos mínimos de sesión","Para identificar el uso del equipo se procesa el nombre y curso declarados, además del nombre/ID del dispositivo, batería, conexión y versión de Android.");Add(p,"✓ Sin grabación por defecto","AulaControl utiliza imágenes temporales para supervisión en vivo y no conserva grabaciones o capturas históricas por defecto.");Add(p,"✓ Cuidado del dispositivo institucional","Los equipos institucionales pueden ser identificados y supervisados técnicamente para su seguridad, custodia, disponibilidad y prevención de pérdida o uso indebido.");var note=T("AulaControl no envía contraseñas ni credenciales personales a servidores del desarrollador. La supervisión se realiza entre la tablet y la consola autorizada del establecimiento.",14,true,Green);note.Margin=new Thickness(0,16,0,0);p.Children.Add(note);var card=Card(p);root.Children.Add(card);var b=new Button{Content="Entendido · continuar",Background=Green,Foreground=Brushes.White,FontSize=15,FontWeight=FontWeights.SemiBold,Padding=new Thickness(18,12,18,12),BorderThickness=new Thickness(0),Margin=new Thickness(0,18,0,6),HorizontalAlignment=HorizontalAlignment.Stretch};b.Click+=(_,_)=>{File.WriteAllText(FlagFile,"AulaControl privacy notice 1.1.2 acknowledged");DialogResult=true;};root.Children.Add(b);var dev=T("AulaControl 1.1.2 · Desarrollador Eduardo Pérez González",12,false,Muted);dev.TextAlignment=TextAlignment.Center;dev.Margin=new Thickness(0,8,0,12);root.Children.Add(dev);Content=sc;}
}
