package cl.antumapu.aulacontrol;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;

public class AgentService extends Service{
 static final int UDP=45888,CMD=45901;static final long IDLE=10*60*1000L,WARN=30*1000L;static final String KEEP="AC_KEEP",LOGOUT="AC_LOGOUT";volatile boolean run,warn;long deadline;ScheduledExecutorService ex;ServerSocket commandSocket;Handler ui=new Handler(Looper.getMainLooper());WindowManager wm;View box;TextView count;
 Runnable tick=new Runnable(){public void run(){if(!warn)return;long r=Math.max(0,deadline-System.currentTimeMillis());int s=(int)Math.ceil(r/1000d);if(count!=null)count.setText("La sesión se cerrará en "+s+" segundos.");warningNote(s);if(r<=0)logout();else ui.postDelayed(this,1000);}};
 @Override public void onCreate(){super.onCreate();startForeground(1001,note("Activo · "+Core.dn(this)));run=true;ex=Executors.newScheduledThreadPool(2);ex.scheduleAtFixedRate(this::beacon,0,3,TimeUnit.SECONDS);ex.scheduleAtFixedRate(this::idle,5,5,TimeUnit.SECONDS);new Thread(this::server,"AulaControlCmd").start();}
 @Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&KEEP.equals(i.getAction()))keep();else if(i!=null&&LOGOUT.equals(i.getAction()))logout();return START_STICKY;}@Override public IBinder onBind(Intent i){return null;}@Override public void onDestroy(){run=false;if(ex!=null)ex.shutdownNow();try{if(commandSocket!=null)commandSocket.close();}catch(Exception ignored){}dismiss();super.onDestroy();}
 void idle(){if(Core.user(this).isEmpty()){if(warn)ui.post(this::dismiss);return;}if(warn)return;long last=Core.activity(this);if(last>Core.last(this))Core.sp(this).edit().putLong("last",last).apply();if(System.currentTimeMillis()-last>=IDLE)ui.post(this::showWarn);}
 void showWarn(){if(warn||Core.user(this).isEmpty())return;warn=true;deadline=System.currentTimeMillis()+WARN;if(Core.overlay(this))try{wm=(WindowManager)getSystemService(WINDOW_SERVICE);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(24),dp(22),dp(24),dp(20));GradientDrawable bg=new GradientDrawable();bg.setColor(Color.WHITE);bg.setCornerRadius(dp(18));l.setBackground(bg);l.addView(txt("¿Seguirás usando esta tablet?",22,true));TextView who=txt(Core.user(this)+(Core.course(this).isEmpty()?"":" · "+Core.course(this)),16,true);who.setTextColor(Color.rgb(15,90,60));l.addView(who);l.addView(txt("Detectamos 10 minutos sin actividad.",15,false));count=txt("La sesión se cerrará en 30 segundos.",16,true);l.addView(count);Button a=new Button(this);a.setText("SEGUIRÉ USANDO");a.setOnClickListener(v->keep());l.addView(a);Button b=new Button(this);b.setText("NO SEGUIRÉ USANDO");b.setOnClickListener(v->logout());l.addView(b);WindowManager.LayoutParams p=new WindowManager.LayoutParams(Math.min(getResources().getDisplayMetrics().widthPixels-dp(32),dp(560)),-2,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_DIM_BEHIND,PixelFormat.TRANSLUCENT);p.gravity=Gravity.CENTER;p.dimAmount=.42f;box=l;wm.addView(box,p);}catch(Exception ignored){}warningNote(30);ui.removeCallbacks(tick);ui.post(tick);}
 void keep(){if(Core.user(this).isEmpty()){dismiss();return;}Core.touch(this);dismiss();beacon();Toast.makeText(this,"La sesión continúa activa",Toast.LENGTH_SHORT).show();}
 void logout(){Core.logout(this);stopService(new Intent(this,ScreenCaptureService.class));dismiss();beacon();try{startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP));}catch(Exception ignored){}Toast.makeText(this,"Sesión cerrada",Toast.LENGTH_LONG).show();}
 void dismiss(){warn=false;ui.removeCallbacks(tick);if(box!=null&&wm!=null)try{wm.removeView(box);}catch(Exception ignored){}box=null;count=null;((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).cancel(1010);}
 void warningNote(int s){Intent ki=new Intent(this,AgentService.class).setAction(KEEP);Intent lo=new Intent(this,AgentService.class).setAction(LOGOUT);PendingIntent kp=PendingIntent.getService(this,201,ki,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);PendingIntent lp=PendingIntent.getService(this,202,lo,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=builder("idle",NotificationManager.IMPORTANCE_HIGH).setContentTitle("¿Sigues usando "+Core.dn(this)+"?").setContentText("Sesión de "+Core.user(this)+" · cierre en "+s+" s").setSmallIcon(android.R.drawable.ic_dialog_alert).setOngoing(true).addAction(new Notification.Action.Builder(null,"Seguiré usando",kp).build()).addAction(new Notification.Action.Builder(null,"No seguiré usando",lp).build()).build();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1010,n);}
 void beacon(){try{String k=Core.key(this);if(k.isEmpty())return;String ip=Core.ip();int bat=battery();long ts=System.currentTimeMillis();boolean managed=Managed.owner(this);long frameAge=ScreenCaptureService.lastFrameAt>0?Math.max(0,ts-ScreenCaptureService.lastFrameAt):-1;JSONObject j=new JSONObject();j.put("type","AULACONTROL_BEACON");j.put("version",4);j.put("schoolTag",Core.sha(k).substring(0,12));j.put("deviceId",Core.id(this));j.put("deviceName",Core.dn(this));j.put("userName",Core.user(this));j.put("course",Core.course(this));j.put("model",Build.MANUFACTURER+" "+Build.MODEL);j.put("android",Build.VERSION.RELEASE);j.put("ip",ip);j.put("commandPort",CMD);j.put("screenPort",ScreenCaptureService.PORT);j.put("screenSharing",ScreenCaptureService.active);j.put("managed",managed);j.put("frameAge",frameAge);j.put("battery",bat);j.put("ts",ts);String d=Core.id(this)+"\n"+Core.dn(this)+"\n"+Core.user(this)+"\n"+Core.course(this)+"\n"+ip+"\n"+CMD+"\n"+ScreenCaptureService.PORT+"\n"+ScreenCaptureService.active+"\n"+managed+"\n"+frameAge+"\n"+bat+"\n"+ts;j.put("sig",Core.hmac(k,d));byte[] b=j.toString().getBytes(StandardCharsets.UTF_8);DatagramSocket s=new DatagramSocket();s.setBroadcast(true);for(InetAddress a:Core.broadcasts())try{s.send(new DatagramPacket(b,b.length,a,UDP));}catch(Exception ignored){}s.close();}catch(Exception ignored){}}
 int battery(){Intent i=registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));if(i==null)return-1;int l=i.getIntExtra("level",-1),s=i.getIntExtra("scale",100);return s>0?(int)(100d*l/s):-1;}
 void server(){try{commandSocket=new ServerSocket(CMD);commandSocket.setReuseAddress(true);while(run)try(Socket c=commandSocket.accept()){c.setSoTimeout(4000);handle(c);}catch(Exception ignored){}}catch(Exception ignored){}finally{commandSocket=null;}}
 void handle(Socket c)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8));String line=r.readLine();if(line==null)return;JSONObject q=new JSONObject(line);String a=q.optString("action"),v=q.optString("value"),sig=q.optString("sig");long ts=q.optLong("ts");boolean ok=Math.abs(System.currentTimeMillis()-ts)<60000&&Core.eq(Core.hmac(Core.key(this),a+"\n"+ts+"\n"+v),sig);String err=ok?action(a,v):"auth";JSONObject o=new JSONObject();o.put("ok",err==null);if(err!=null)o.put("error",err);c.getOutputStream().write((o+"\n").getBytes(StandardCharsets.UTF_8));}
 String action(String a,String v){switch(a){case"PING":return null;case"MESSAGE":message(v);return null;case"OPEN_URL":url(v);return null;case"REQUEST_SCREEN":screenRequest();return null;case"STOP_SCREEN":stopService(new Intent(this,ScreenCaptureService.class));return null;case"FORCE_LOGOUT":ui.post(this::logout);return null;default:return"unknown";}}
 void message(String v){Notification n=builder("msg",NotificationManager.IMPORTANCE_HIGH).setContentTitle("Mensaje del docente").setContentText(v).setStyle(new Notification.BigTextStyle().bigText(v)).setSmallIcon(android.R.drawable.ic_dialog_info).build();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1003,n);}void url(String v){try{Uri u=Uri.parse(v);if(!"http".equalsIgnoreCase(u.getScheme())&&!"https".equalsIgnoreCase(u.getScheme()))return;Intent i=new Intent(Intent.ACTION_VIEW,u);PendingIntent p=PendingIntent.getActivity(this,88,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=builder("url",NotificationManager.IMPORTANCE_HIGH).setContentTitle("Enlace del docente").setContentText(v).setSmallIcon(android.R.drawable.ic_menu_view).setContentIntent(p).setAutoCancel(true).build();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1004,n);}catch(Exception ignored){}}
 void screenRequest(){try{startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP));}catch(Exception ignored){}}
 Notification note(String x){return builder("agent",NotificationManager.IMPORTANCE_LOW).setContentTitle("AulaControl").setContentText(x).setSmallIcon(android.R.drawable.presence_online).setOngoing(true).build();}Notification.Builder builder(String ch,int imp){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26&&nm.getNotificationChannel(ch)==null)nm.createNotificationChannel(new NotificationChannel(ch,"AulaControl",imp));return Build.VERSION.SDK_INT>=26?new Notification.Builder(this,ch):new Notification.Builder(this);}TextView txt(String s,int z,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.rgb(25,30,38));if(b)t.setTypeface(null,1);return t;}int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
}
