package cl.antumapu.aulacontrol;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.widget.*;

public class CleanupRecoveryActivity extends Activity{
 static final int GREEN=Color.rgb(15,90,60),DARK=Color.rgb(8,56,38),ORANGE=Color.rgb(243,107,33),RED=Color.rgb(177,50,50),MUTED=Color.rgb(94,111,103),BG=Color.rgb(244,248,246);Handler ui=new Handler(Looper.getMainLooper());
 @Override public void onCreate(Bundle b){super.onCreate(b);Managed.enter(this);showGuard();}
 @Override protected void onResume(){super.onResume();if(!GuestSession.requiresIntervention(this)&&!GuestSession.cleaning(this)){go();return;}Managed.enter(this);}
 @Override public void onBackPressed(){showGuard();}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}TextView t(String s,int z,boolean bold,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(color);if(bold)v.setTypeface(null,1);v.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);return v;}Button b(String s,int color){Button x=new Button(this);x.setText(s);x.setTextColor(Color.WHITE);x.setTextSize(15);x.setTypeface(null,1);x.setAllCaps(false);x.setBackground(bg(color,14));x.setPadding(dp(15),dp(12),dp(15),dp(12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));x.setLayoutParams(p);return x;}
 void showGuard(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(26),dp(30),dp(26),dp(30));r.setBackgroundColor(BG);TextView brand=t("AulaControl",31,true,DARK);r.addView(brand);TextView tag=t("Protección de sesión",16,true,ORANGE);tag.setPadding(0,dp(2),0,dp(18));r.addView(tag);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(22),dp(22),dp(22),dp(22));c.setBackground(bg(Color.WHITE,20));TextView h=t("La tablet permanece bloqueada",24,true,DARK);c.addView(h);TextView m=t("AulaControl no pudo confirmar que todas las aplicaciones de la sesión anterior quedaron restablecidas. Para proteger al siguiente usuario, no se habilitará una nueva sesión hasta completar la limpieza.",14,false,MUTED);m.setPadding(0,dp(10),0,dp(14));c.addView(m);TextView status=t(GuestSession.status(this),13,true,RED);c.addView(status);Button retry=b("Reintentar limpieza",GREEN);Button admin=b("Mantenimiento administrador",DARK);c.addView(retry);c.addView(admin);r.addView(c,new LinearLayout.LayoutParams(-1,-2));retry.setOnClickListener(v->{GuestSession.begin(this);showProgress();});admin.setOnClickListener(v->askAdmin());setContentView(r);}
 void showProgress(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(28),dp(28),dp(28),dp(28));r.setBackgroundColor(BG);r.addView(t("Restableciendo la tablet",25,true,DARK));ProgressBar p=new ProgressBar(this);r.addView(p,new LinearLayout.LayoutParams(-1,dp(72)));TextView s=t(GuestSession.status(this),14,false,MUTED);r.addView(s);setContentView(r);Runnable[] poll=new Runnable[1];poll[0]=()->{s.setText(GuestSession.status(this));if(GuestSession.cleaning(this)){ui.postDelayed(poll[0],500);return;}if(GuestSession.lastCleanupOk(this))go();else showGuard();};ui.postDelayed(poll[0],500);}
 void askAdmin(){EditText p=new EditText(this);p.setHint("Contraseña administrativa");p.setSingleLine(true);p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);p.setPadding(dp(16),dp(12),dp(16),dp(12));new AlertDialog.Builder(this).setTitle("Acceso administrador").setMessage("Sólo mantenimiento autorizado puede salir del bloqueo de seguridad.").setView(p).setNegativeButton("Cancelar",null).setPositiveButton("Desbloquear",(d,w)->{if(!Core.checkPw(this,p.getText().toString())){Toast.makeText(this,"Contraseña incorrecta",Toast.LENGTH_SHORT).show();return;}Managed.exit(this);new AlertDialog.Builder(this).setTitle("Modo mantenimiento").setMessage("Puedes abrir Ajustes para diagnóstico o liberar Device Owner si necesitas retirar AulaControl. Al volver a la app, las restricciones se activarán nuevamente.").setNegativeButton("Volver a proteger",(a,z)->{Managed.apply(this);showGuard();}).setNeutralButton("Liberar dispositivo",(a,z)->confirmRelease()).setPositiveButton("Abrir Ajustes",(a,z)->{try{startActivity(new Intent(Settings.ACTION_SETTINGS));}catch(Exception ignored){}}).show();}).show();}
 void confirmRelease(){new AlertDialog.Builder(this).setTitle("Liberar dispositivo").setMessage("Esto retirará la protección administrativa y permitirá desinstalar AulaControl. Úsalo sólo para mantenimiento autorizado.").setNegativeButton("Cancelar",null).setPositiveButton("LIBERAR",(d,w)->{boolean ok=Managed.release(this);Toast.makeText(this,ok?"Dispositivo liberado":"No fue posible liberar el dispositivo",Toast.LENGTH_LONG).show();if(ok)go();else showGuard();}).show();}
 void go(){Intent i=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);startActivity(i);finish();}
}
