package cl.antumapu.aulacontrol;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.media.projection.MediaProjectionManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.widget.*;

public class MainActivity extends Activity{
 static final int CAP=42,USAGE=43,OVERLAY=44; EditText user,course; TextView state,card;
 @Override public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},9);if(Core.ready(this)){agent();mainUi();}else firstUi();if("CAPTURE".equals(getIntent().getAction()))capture();}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);if("CAPTURE".equals(i.getAction()))capture();}
 @Override public void onUserInteraction(){super.onUserInteraction();if(!Core.user(this).isEmpty())Core.touch(this);} @Override protected void onResume(){super.onResume();if(state!=null)refresh();}
 LinearLayout root(){var r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(26),dp(26),dp(26),dp(26));r.setBackgroundColor(Color.rgb(247,249,252));return r;}
 TextView t(String s,int z,boolean b){var v=new TextView(this);v.setText(s);v.setTextSize(z);if(b)v.setTypeface(null,1);return v;} EditText in(String h,String v){var e=new EditText(this);e.setHint(h);e.setText(v);e.setTextSize(17);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackgroundColor(Color.WHITE);var p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));e.setLayoutParams(p);return e;} EditText pw(String h){var e=in(h,"");e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;} Button btn(String s){var b=new Button(this);b.setText(s);var p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(4));b.setLayoutParams(p);return b;} int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 void firstUi(){ScrollView sc=new ScrollView(this);LinearLayout r=root();sc.addView(r);r.addView(t("AulaControl",30,true));r.addView(t("Configuración inicial",16,false));r.addView(t("\nID permanente: "+Core.id(this)+"\n",18,true));var dn=in("Nombre del dispositivo (ej. Tablet 01)","");var key=in("Clave técnica del aula / establecimiento","");EditText p1=pw("Contraseña de configuración");EditText p2=pw("Repite la contraseña");r.addView(dn);r.addView(key);r.addView(p1);r.addView(p2);r.addView(t("La contraseña protege únicamente la configuración. La clave técnica vincula tablets y consola Windows.",14,false));var b=btn("ACTIVAR AULACONTROL");r.addView(b);b.setOnClickListener(v->{String a=dn.getText().toString().trim(),k=key.getText().toString().trim(),p=p1.getText().toString();if(a.length()<2){toast("Asigna un nombre al dispositivo");return;}if(k.length()<10){toast("La clave técnica debe tener al menos 10 caracteres");return;}if(p.length()<6){toast("La contraseña debe tener al menos 6 caracteres");return;}if(!p.equals(p2.getText().toString())){toast("Las contraseñas no coinciden");return;}Core.setup(this,a,k,p);agent();mainUi();new Handler(Looper.getMainLooper()).postDelayed(this::permissions,400);});setContentView(sc);}
 void mainUi(){ScrollView sc=new ScrollView(this);LinearLayout r=root();sc.addView(r);var h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);var title=t("AulaControl",30,true);h.addView(title,new LinearLayout.LayoutParams(0,-2,1));var cfg=btn("⚙ CONFIGURAR");cfg.setLayoutParams(new LinearLayout.LayoutParams(-2,-2));h.addView(cfg);r.addView(h);cfg.setOnClickListener(v->askPw(this::config));card=t("",18,true);card.setPadding(dp(16),dp(16),dp(16),dp(16));card.setBackgroundColor(Color.WHITE);r.addView(card);if(!Core.usage(this)||!Core.overlay(this)){var w=t("\n⚠ Para el cierre automático de sesión habilita Acceso de uso y Mostrar sobre otras apps.",14,false);r.addView(w);var pb=btn("CONFIGURAR PERMISOS DE INACTIVIDAD");r.addView(pb);pb.setOnClickListener(v->askPw(this::permissions));}r.addView(t("\nIdentificación del usuario",18,true));r.addView(t("El nombre será visible en el computador de monitoreo. Tras 10 minutos sin actividad se avisará durante 30 segundos antes de cerrar la sesión.",14,false));user=in("Nombre y apellido",Core.user(this));course=in("Curso",Core.course(this));r.addView(user);r.addView(course);var login=btn("INICIAR / ACTUALIZAR SESIÓN");r.addView(login);login.setOnClickListener(v->{String u=user.getText().toString().trim();if(u.isEmpty()){toast("Ingresa el nombre del estudiante");return;}Core.login(this,u,course.getText().toString());agent();refresh();});var out=btn("CERRAR SESIÓN DEL ESTUDIANTE");r.addView(out);out.setOnClickListener(v->{Core.logout(this);stopService(new Intent(this,ScreenCaptureService.class));user.setText("");course.setText("");refresh();});r.addView(t("\nPantalla",18,true));var share=btn("COMPARTIR PANTALLA CON EL DOCENTE");r.addView(share);share.setOnClickListener(v->capture());var stop=btn("DETENER COMPARTIR PANTALLA");r.addView(stop);stop.setOnClickListener(v->stopService(new Intent(this,ScreenCaptureService.class)));state=t("",15,false);state.setPadding(0,dp(18),0,0);r.addView(state);setContentView(sc);refresh();}
 void askPw(Runnable ok){var p=pw("Contraseña de configuración");new AlertDialog.Builder(this).setTitle("Configuración protegida").setView(p).setNegativeButton("Cancelar",null).setPositiveButton("Continuar",(d,w)->{if(Core.checkPw(this,p.getText().toString()))ok.run();else toast("Contraseña incorrecta");}).show();}
 void config(){var box=root();box.setPadding(dp(18),dp(6),dp(18),dp(6));var dn=in("Nombre del dispositivo",Core.dn(this));var k=in("Clave técnica",Core.key(this));EditText np=pw("Nueva contraseña (opcional)");EditText cp=pw("Repite nueva contraseña");box.addView(dn);box.addView(k);box.addView(np);box.addView(cp);new AlertDialog.Builder(this).setTitle("Configuración").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",(d,w)->{String a=dn.getText().toString().trim(),x=k.getText().toString().trim(),p=np.getText().toString();if(a.length()<2||x.length()<10){toast("Revisa nombre y clave técnica");return;}if(!p.isEmpty()&&(p.length()<6||!p.equals(cp.getText().toString()))){toast("Revisa la nueva contraseña");return;}Core.config(this,a,x,p);stopService(new Intent(this,AgentService.class));agent();mainUi();}).show();}
 void permissions(){if(!Core.usage(this)){startActivityForResult(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS),USAGE);return;}if(!Core.overlay(this)){startActivityForResult(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, Uri.parse("package:"+getPackageName())),OVERLAY);return;}toast("Permisos de inactividad configurados");mainUi();}
 void agent(){if(!Core.ready(this))return;var i=new Intent(this,AgentService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);} void capture(){if(!Core.ready(this))return;var m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);startActivityForResult(m.createScreenCaptureIntent(),CAP);} 
 @Override protected void onActivityResult(int rq,int rc,Intent data){super.onActivityResult(rq,rc,data);if(rq==CAP&&rc==RESULT_OK&&data!=null){var i=new Intent(this,ScreenCaptureService.class);i.putExtra("rc",rc);i.putExtra("data",data);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);toast("Pantalla compartida");}else if(rq==USAGE||rq==OVERLAY)new Handler(Looper.getMainLooper()).postDelayed(this::permissions,250);}
 void refresh(){if(card!=null)card.setText(Core.dn(this)+"\nID: "+Core.id(this));if(state!=null)state.setText("● Monitoreo activo\n"+(Core.user(this).isEmpty()?"Sin usuario identificado":"Usuario: "+Core.user(this)+(Core.course(this).isEmpty()?"":" · "+Core.course(this)))+"\nCierre automático: "+((Core.usage(this)&&Core.overlay(this))?"listo":"permisos pendientes")+"\nIP: "+Core.ip());}
}
