package cl.antumapu.aulacontrol;

import android.Manifest;import android.app.*;import android.app.admin.*;import android.content.*;import android.content.pm.*;import android.os.*;import java.util.*;

final class Managed{
 private Managed(){}
 static ComponentName admin(Context c){return new ComponentName(c,AdminReceiver.class);} static DevicePolicyManager dpm(Context c){return (DevicePolicyManager)c.getSystemService(Context.DEVICE_POLICY_SERVICE);} 
 static boolean owner(Context c){try{return dpm(c).isDeviceOwnerApp(c.getPackageName());}catch(Exception e){return false;}} static boolean profileOwner(Context c){try{return dpm(c).isProfileOwnerApp(c.getPackageName());}catch(Exception e){return false;}} static boolean managed(Context c){return owner(c)||profileOwner(c);}
 static void restriction(DevicePolicyManager d,ComponentName a,String key,boolean on){try{if(on)d.addUserRestriction(a,key);else d.clearUserRestriction(a,key);}catch(Exception ignored){}}
 static void apply(Context c){if(owner(c))applyOwner(c);else if(profileOwner(c))applyGuest(c);}
 static void applyOwner(Context c){try{DevicePolicyManager d=dpm(c);ComponentName a=admin(c);String self=c.getPackageName();d.setAffiliationIds(a,Collections.singleton(SessionUsers.AFFILIATION));d.setUninstallBlocked(a,self,true);restriction(d,a,UserManager.DISALLOW_UNINSTALL_APPS,true);restriction(d,a,UserManager.DISALLOW_APPS_CONTROL,true);restriction(d,a,UserManager.DISALLOW_FACTORY_RESET,true);restriction(d,a,UserManager.DISALLOW_SAFE_BOOT,true);restriction(d,a,UserManager.DISALLOW_INSTALL_UNKNOWN_SOURCES,true);restriction(d,a,UserManager.DISALLOW_DEBUGGING_FEATURES,true);if(Build.VERSION.SDK_INT>=30)try{d.setUserControlDisabledPackages(a,Collections.singletonList(self));}catch(Exception ignored){}if(Build.VERSION.SDK_INT>=33)try{d.setPermissionGrantState(a,self,Manifest.permission.POST_NOTIFICATIONS,DevicePolicyManager.PERMISSION_GRANT_STATE_GRANTED);}catch(Exception ignored){}IntentFilter f=new IntentFilter(Intent.ACTION_MAIN);f.addCategory(Intent.CATEGORY_HOME);f.addCategory(Intent.CATEGORY_DEFAULT);d.addPersistentPreferredActivity(a,f,new ComponentName(c,PrivacyGateActivity.class));}catch(Exception ignored){}}
 static void applyGuest(Context c){try{DevicePolicyManager d=dpm(c);ComponentName a=admin(c);String self=c.getPackageName();d.setAffiliationIds(a,Collections.singleton(SessionUsers.AFFILIATION));d.setUninstallBlocked(a,self,true);restriction(d,a,UserManager.DISALLOW_UNINSTALL_APPS,true);restriction(d,a,UserManager.DISALLOW_INSTALL_APPS,true);restriction(d,a,UserManager.DISALLOW_INSTALL_UNKNOWN_SOURCES,true);restriction(d,a,UserManager.DISALLOW_DEBUGGING_FEATURES,true);restriction(d,a,UserManager.DISALLOW_ADD_USER,true);restriction(d,a,UserManager.DISALLOW_USER_SWITCH,true);restriction(d,a,UserManager.DISALLOW_APPS_CONTROL,true);restriction(d,a,UserManager.DISALLOW_MODIFY_ACCOUNTS,false);restriction(d,a,UserManager.DISALLOW_CONFIG_WIFI,false);restriction(d,a,UserManager.DISALLOW_BLUETOOTH,false);if(Build.VERSION.SDK_INT>=33)try{d.setPermissionGrantState(a,self,Manifest.permission.POST_NOTIFICATIONS,DevicePolicyManager.PERMISSION_GRANT_STATE_GRANTED);}catch(Exception ignored){}preferOriginalHome(c,d,a);}catch(Exception ignored){}}
 static void preferOriginalHome(Context c,DevicePolicyManager d,ComponentName a){try{Intent q=new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME);List<ResolveInfo> rs=c.getPackageManager().queryIntentActivities(q,PackageManager.MATCH_ALL);for(ResolveInfo r:rs){if(r.activityInfo==null||c.getPackageName().equals(r.activityInfo.packageName))continue;IntentFilter f=new IntentFilter(Intent.ACTION_MAIN);f.addCategory(Intent.CATEGORY_HOME);f.addCategory(Intent.CATEGORY_DEFAULT);d.addPersistentPreferredActivity(a,f,new ComponentName(r.activityInfo.packageName,r.activityInfo.name));break;}}catch(Exception ignored){}}
 static void enterGate(Activity a){if(owner(a)){applyOwner(a);try{a.startLockTask();}catch(Exception ignored){}}}
 static void adminUnlock(Context c){if(!managed(c))return;try{DevicePolicyManager d=dpm(c);ComponentName a=admin(c);restriction(d,a,UserManager.DISALLOW_UNINSTALL_APPS,false);restriction(d,a,UserManager.DISALLOW_INSTALL_APPS,false);restriction(d,a,UserManager.DISALLOW_APPS_CONTROL,false);restriction(d,a,UserManager.DISALLOW_INSTALL_UNKNOWN_SOURCES,false);restriction(d,a,UserManager.DISALLOW_DEBUGGING_FEATURES,false);restriction(d,a,UserManager.DISALLOW_FACTORY_RESET,false);d.setUninstallBlocked(a,c.getPackageName(),false);try{d.setStatusBarDisabled(a,false);}catch(Exception ignored){}}catch(Exception ignored){}}
 static void restoreProtection(Context c){Core.adminMode(c,false);apply(c);}
 static void exitGate(Activity a){try{a.stopLockTask();}catch(Exception ignored){}}
 static void enter(Activity a){enterGate(a);} static void exit(Activity a){exitGate(a);adminUnlock(a);}
 @SuppressWarnings("deprecation") static boolean release(Context c){if(!owner(c))return false;try{adminUnlock(c);DevicePolicyManager d=dpm(c);ComponentName a=admin(c);d.clearPackagePersistentPreferredActivities(a,c.getPackageName());d.clearDeviceOwnerApp(c.getPackageName());return true;}catch(Exception e){return false;}}
}
