package cl.antumapu.aulacontrol;

import android.app.*;import android.content.*;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import android.util.DisplayMetrics;import java.io.*;import java.net.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.atomic.AtomicReference;

public class ScreenCaptureService extends Service{
 public static final int PORT=45902;public static volatile boolean active=false;public static volatile long lastFrameAt=0;MediaProjection mp;VirtualDisplay vd;ImageReader ir;volatile boolean run;AtomicReference<byte[]> frame=new AtomicReference<>();long last;ServerSocket screenSocket;
 @Override public int onStartCommand(Intent i,int f,int id){startForeground(2001,note());int rc=i==null?0:i.getIntExtra("rc",0);Intent data=null;if(i!=null)data=Build.VERSION.SDK_INT>=33?i.getParcelableExtra("data",Intent.class):(Intent)i.getParcelableExtra("data");if(rc!=0&&data!=null)start(rc,data);return START_NOT_STICKY;}@Override public IBinder onBind(Intent i){return null;}
 @Override public void onDestroy(){run=false;active=false;lastFrameAt=0;try{if(screenSocket!=null)screenSocket.close();}catch(Exception ignored){}if(vd!=null)vd.release();if(ir!=null)ir.close();if(mp!=null)try{mp.stop();}catch(Exception ignored){}if(!Core.user(this).isEmpty())bringLauncher();super.onDestroy();}
 void start(int rc,Intent data){if(active)return;MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);mp=m.getMediaProjection(rc,data);if(mp==null){stopSelf();return;}active=run=true;lastFrameAt=0;mp.registerCallback(new MediaProjection.Callback(){@Override public void onStop(){active=false;lastFrameAt=0;bringLauncher();stopSelf();}},new Handler(Looper.getMainLooper()));DisplayMetrics dm=getResources().getDisplayMetrics();int w=Math.min(720,dm.widthPixels),h=(int)(dm.heightPixels*(w/(double)dm.widthPixels));ir=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);ir.setOnImageAvailableListener(r->{Image im=null;try{im=r.acquireLatestImage();if(im==null)return;long n=System.currentTimeMillis();if(n-last<450)return;last=n;Image.Plane p=im.getPlanes()[0];ByteBuffer b=p.getBuffer();int ps=p.getPixelStride(),rs=p.getRowStride(),pad=rs-ps*w;Bitmap wide=Bitmap.createBitmap(w+pad/ps,h,Bitmap.Config.ARGB_8888);wide.copyPixelsFromBuffer(b);Bitmap crop=Bitmap.createBitmap(wide,0,0,w,h);ByteArrayOutputStream out=new ByteArrayOutputStream();crop.compress(Bitmap.CompressFormat.JPEG,58,out);frame.set(out.toByteArray());lastFrameAt=System.currentTimeMillis();wide.recycle();crop.recycle();}catch(Exception ignored){}finally{if(im!=null)im.close();}},new Handler(Looper.getMainLooper()));vd=mp.createVirtualDisplay("AulaControl",w,h,dm.densityDpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,ir.getSurface(),null,null);new Thread(this::server,"AulaControlScreen").start();}
 void bringLauncher(){try{Intent i=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);startActivity(i);}catch(Exception ignored){}}
 void server(){try{screenSocket=new ServerSocket(PORT);screenSocket.setReuseAddress(true);while(run)try(Socket c=screenSocket.accept()){c.setSoTimeout(3000);serve(c);}catch(Exception ignored){}}catch(Exception ignored){}finally{screenSocket=null;}}
 void serve(Socket c)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.US_ASCII));if(r.readLine()==null)return;String ts="",sig="",l;while((l=r.readLine())!=null&&!l.isEmpty()){int x=l.indexOf(':');if(x>0){String k=l.substring(0,x).trim(),v=l.substring(x+1).trim();if(k.equalsIgnoreCase("X-Timestamp"))ts=v;if(k.equalsIgnoreCase("X-Signature"))sig=v;}}boolean ok=false;try{long t=Long.parseLong(ts);ok=Math.abs(System.currentTimeMillis()-t)<60000&&Core.eq(Core.hmac(Core.key(this),"SCREEN\n"+t),sig);}catch(Exception ignored){}byte[] b=frame.get();if(!ok){write(c,403,"text/plain","forbidden".getBytes(StandardCharsets.UTF_8));return;}if(b==null){write(c,503,"text/plain","waiting".getBytes(StandardCharsets.UTF_8));return;}write(c,200,"image/jpeg",b);}
 void write(Socket c,int code,String type,byte[] b)throws IOException{OutputStream o=c.getOutputStream();String h="HTTP/1.1 "+code+" OK\r\nContent-Type: "+type+"\r\nContent-Length: "+b.length+"\r\nConnection: close\r\n\r\n";o.write(h.getBytes(StandardCharsets.US_ASCII));o.write(b);o.flush();}
 Notification note(){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);String c="capture";if(Build.VERSION.SDK_INT>=26&&nm.getNotificationChannel(c)==null)nm.createNotificationChannel(new NotificationChannel(c,"Sesión supervisada",NotificationManager.IMPORTANCE_LOW));Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,c):new Notification.Builder(this);return b.setContentTitle("AulaControl").setContentText("Sesión supervisada activa").setSmallIcon(android.R.drawable.presence_online).setOngoing(true).build();}
}
