package cl.antumapu.pangi.v205;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.widget.*;

public class CleanupRecoveryActivity extends Activity{
 static final int BLUE=Color.rgb(49,89,255),NAVY=Color.rgb(23,43,77),TEAL=Color.rgb(32,199,164),RED=Color.rgb(202,61,71),INK=Color.rgb(23,32,51),MUTED=Color.rgb(102,112,133),BG=Color.rgb(244,247,251),LINE=Color.rgb(221,228,239);Handler ui=new Handler(Looper.getMainLooper());
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);Managed.enter(this);showGuard();}
 @Override protected void onResume(){super.onResume();if(!GuestSession.requiresIntervention(this)&&!GuestSession.cleaning(this)){go();return;}Managed.enter(this);}
 @Override public void onBackPressed(){showGuard();}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}GradientDrawable outline(int fill,int stroke,int r){GradientDrawable g=shape(fill,r);g.setStroke(dp(1),stroke);return g;}TextView t(String s,int z,boolean bold,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(color);if(bold)v.setTypeface(null,1);v.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);return v;}Button b(String s,int fill,int fg,int stroke){Button x=new Button(this);x.setText(s);x.setTextColor(fg);x.setTextSize(15);x.setTypeface(null,1);x.setAllCaps(false);x.setBackground(stroke==0?shape(fill,14):outline(fill,stroke,14));x.setPadding(dp(15),dp(12),dp(15),dp(12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));x.setLayoutParams(p);return x;}
 void brand(LinearLayout r){LinearLayout mark=new LinearLayout(this);mark.setGravity(Gravity.CENTER);mark.setBackground(shape(BLUE,20));ImageView icon=new ImageView(this);icon.setImageResource(R.drawable.ic_tablet_school_mark);mark.addView(icon,new LinearLayout.LayoutParams(dp(58),dp(58)));r.addView(mark,new LinearLayout.LayoutParams(dp(72),dp(72)));TextView brand=t("PANGI",27,true,NAVY);brand.setPadding(0,dp(12),0,0);r.addView(brand);TextView tag=t("Protección de sesión",14,true,TEAL);tag.setPadding(0,dp(2),0,dp(18));r.addView(tag);}
 void showGuard(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(26),dp(30),dp(26),dp(30));r.setBackgroundColor(BG);brand(r);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(22),dp(22),dp(22),dp(22));c.setBackground(outline(Color.WHITE,LINE,20));TextView h=t("La tablet permanece protegida",24,true,INK);c.addView(h);TextView m=t("No se pudo confirmar que la sesión anterior quedó completamente restablecida. Para proteger al siguiente usuario, PANGI no habilitará una nueva sesión hasta completar la limpieza.",14,false,MUTED);m.setPadding(0,dp(10),0,dp(14));c.addView(m);TextView status=t(GuestSession.status(this),13,true,RED);c.addView(status);Button retry=b("Reintentar limpieza",BLUE,Color.WHITE,0);Button admin=b("Mantenimiento administrador",Color.WHITE,NAVY,LINE);c.addView(retry);c.addView(admin);r.addView(c,new LinearLayout.LayoutParams(-1,-2));retry.setOnClickListener(v->{GuestSession.begin(this);showProgress();});admin.setOnClickListener(v->askAdmin());setContentView(r);}
 void showProgress(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(28),dp(28),dp(28),dp(28));r.setBackgroundColor(BG);brand(r);r.addView(t("Restableciendo la tablet",25,true,INK));ProgressBar p=new ProgressBar(this);r.addView(p,new LinearLayout.LayoutParams(-1,dp(72)));TextView s=t(GuestSession.status(this),14,false,MUTED);r.addView(s);setContentView(r);Runnable[] poll=new Runnable[1];poll[0]=()->{s.setText(GuestSession.status(this));if(GuestSession.cleaning(this)){ui.postDelayed(poll[0],500);return;}if(GuestSession.lastCleanupOk(this))go();else showGuard();};ui.postDelayed(poll[0],500);}
 void askAdmin(){EditText p=new EditText(this);p.setHint("Contraseña administrativa");p.setSingleLine(true);p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);p.setPadding(dp(16),dp(12),dp(16),dp(12));new AlertDialog.Builder(this).setTitle("Administración de PANGI").setMessage("Sólo mantenimiento autorizado puede salir de este bloqueo de seguridad.").setView(p).setNegativeButton("Cancelar",null).setPositiveButton("Desbloquear",(d,w)->{if(!Core.checkPw(this,p.getText().toString())){Toast.makeText(this,"Contraseña incorrecta",Toast.LENGTH_SHORT).show();return;}Managed.exit(this);new AlertDialog.Builder(this).setTitle("Modo mantenimiento").setMessage("Puedes abrir Ajustes para diagnóstico o liberar Device Owner. Al volver a la aplicación, las restricciones se activarán nuevamente.").setNegativeButton("Volver a proteger",(a,z)->{Managed.apply(this);showGuard();}).setNeutralButton("Liberar dispositivo",(a,z)->confirmRelease()).setPositiveButton("Abrir Ajustes",(a,z)->{try{startActivity(new Intent(Settings.ACTION_SETTINGS));}catch(Exception ignored){}}).show();}).show();}
 void confirmRelease(){new AlertDialog.Builder(this).setTitle("Liberar dispositivo").setMessage("Esto retirará la administración institucional y permitirá desinstalar PANGI. Úsalo sólo para mantenimiento autorizado.").setNegativeButton("Cancelar",null).setPositiveButton("LIBERAR",(d,w)->{boolean ok=Managed.release(this);Toast.makeText(this,ok?"Dispositivo liberado":"No fue posible liberar el dispositivo",Toast.LENGTH_LONG).show();if(ok)go();else showGuard();}).show();}
 void go(){Intent i=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);startActivity(i);finish();}
}
